#https://raw.githubusercontent.com/brightbox/puppet/master/Rakefile#
task :default => [:test, :parse]

desc "Noop implementation of default task"
task :clean do
end

desc "Run the test suite"
task :test do
	pcommand = "puppet apply"
	Dir["tests/*pp"].each do |test_file|
		sh "#{pcommand} --noop --modulepath ..:../3rdparty #{test_file} 2>&1 | grep -v 'Warning: Unacceptable location.'"
	end
end

desc "Parse any .pp files we can find"
task :parse => :clean do
	pcommand = "puppet parser validate --modulepath ..:../3rdparty"

	files = Dir["manifests/**/*.pp", "modules/**/*.pp"]
	sh "#{pcommand} #{files.join(' ')}"
end

desc "Run lint check on puppet manifests"
task :lint => :clean do
	require 'puppet-lint'
	linter =  PuppetLint.new
	linter.configuration.send('disable_140chars')
	linter.configuration.send('disable_2sp_soft_tabs')
	linter.configuration.send('disable_hard_tabs')
	Dir.glob('./**/*.pp').each do |puppet_file|
		puts "=== Evaluating #{puppet_file}"
		linter.file = puppet_file
		linter.run
		linter.print_problems
	end
	fail if linter.errors?
end

desc "Generate documentation from READMEs and manifests"
task :doc do
	sh "python /puppet/metalib/bin/generate_module_doc.py"
end

